name: Liapp Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: login to docker hub
      id: docker-hub
      env:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_PASSWORD}}
      run: |
        docker login -u $username -p $password
    - name: Build the Docker image
      id: docker-image
      run: docker build ./liapp --file ./liapp/Dockerfile --tag miked7676/liapp:interview
    - name: Run Container
      id: docker-container
      run:
        docker run -d -p 80:80 miked7676/liapp:interview
    - name: run tests
      id: liatrioctests
      uses: liatrio/github-actions/apprentice-action@master
    - name: push the docker image
      id: push-docker-image
      run: docker push ${{secrets.DOCKERHUB_USERNAME}}/liapp:interview