name: Liapp Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: login to docker hub
      id: docker-hub
      env:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_PASSWORD}}
      run: |
        docker login -u $username -p $password
    - name: Build the Docker image
      run: docker build ./liapp --file ./liapp/Dockerfile --tag miked7676/liapp:interview
    - name: start server
      run:
        docker run -d -p 80:8080 miked7676/liapp:interview
    - name: run tests
      uses: liatrio/github-actions/apprentice-action@master
    - name: push the docker image
      id: push-docker-image
      run: docker push ${{secrets.DOCKERHUB_USERNAME}}/liapp:interview