name: Liapp Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: login to docker hub
      uses: docker/login-action@v3
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_PASSWORD}}
        
    - name: Build the Docker image
      id: docker-image
      run: docker build ./liapp --file ./liapp/Dockerfile --tag miked7676/liapp:interview
    - name: Run Container
      id: docker-container
      run:
        docker run -d -p 80:8080 miked7676/liapp:interview
    - name: run tests
      id: liatriotests
      uses: liatrio/github-actions/apprentice-action@0b41561cca6822cc8d880fe0e49e7807a41fdf91
    - name: push the docker image
      id: push-docker-image
      run: docker push miked7676/liapp:interview
    - name: Google Cloud Login
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{secrets.GOOGLE_CREDENTIALS}}